/* Dispensasi: summary and log views share one modular filter/table engine. */
const DispensasiModule = {
  logColumns: ['No', 'Timestamp', 'NIP', 'Nama', 'Unit', 'Jenis Dispensasi', 'Uraian', 'Jam Keluar', 'Jam Kembali', 'Durasi', 'Status', 'Lokasi Keluar', 'Lokasi Kembali', 'Bukti Surat', 'Bukti Foto'],
  state: { rawData: [], logData: [], logFields: [], filteredData: [], searchQuery: '', yearFilter: 'Semua', monthFilter: 'Semua', unitFilter: 'Semua', jenisFilter: 'Semua', statusFilter: 'Semua', sortColumn: null, sortDirection: 'asc', currentPage: 1, pageSize: 100 },

  async render(container, rawArray) {
    this.state.rawData = Array.isArray(rawArray) ? rawArray : [];
    container.innerHTML = `${this.summaryMarkup()}<section id="dispensasiLogSection" class="dispensasi-log-section"><div class="investment-tab-loading"><i class="fas fa-circle-notch fa-spin"></i> Memuat log dispensasi...</div></section>`;
    this.renderSummaryCharts();
    await this.loadLog();
  },

  findField(fields, pattern) { return fields.find(field => pattern.test(field)); },
  value(row, fields, pattern) { const field = this.findField(fields, pattern); return field ? row[field] : ''; },
  classifyJenis(value) { return /dinas|kedinasan|tugas/i.test(String(value)) ? 'Kedinasan' : 'Pribadi'; },

  renderLogSection() { const section = document.getElementById('dispensasiLogSection'); if (!section) return; section.innerHTML = this.logMarkup(); this.populateLogFilters(); this.renderLogTable(); this.bindLogEvents(); },

  summaryMarkup() {
    const raw = this.state.rawData, fields = SchemaDetector.detectFields(raw);
    const jenis = row => this.value(row, fields, /jenis|kategori/i), status = row => this.value(row, fields, /status/i), duration = row => parseFloat(this.value(row, fields, /durasi|menit/i)) || 0;
    const kedinasan = raw.filter(row => this.classifyJenis(jenis(row)) === 'Kedinasan').length;
    const pribadi = raw.filter(row => this.classifyJenis(jenis(row)) === 'Pribadi').length;
    const berjalan = raw.filter(row => /berjalan|proses|aktif/i.test(status(row))).length;
    const tepatWaktu = raw.filter(row => /tepat/i.test(status(row)) || /tepat/i.test(this.value(row, fields, /status.*durasi/i))).length;
    const avgDuration = raw.length ? raw.reduce((sum, row) => sum + duration(row), 0) / raw.length : 0;
    const pegawai = new Set(raw.map(row => this.value(row, fields, /\bnip\b/i) || this.value(row, fields, /nama/i)).filter(Boolean)).size;
    const metrics = [['Total Dispensasi', raw.length, 'fa-file-invoice'], ['Dispensasi Kedinasan', kedinasan, 'fa-briefcase'], ['Dispensasi Pribadi', pribadi, 'fa-user'], ['Sedang Berjalan', berjalan, 'fa-clock'], ['Tepat Waktu', tepatWaktu, 'fa-check-circle'], ['Rata-rata Durasi', `${Math.round(avgDuration)} Menit`, 'fa-stopwatch'], ['Pegawai Melakukan Dispensasi', pegawai, 'fa-users']];
    return `<div class="stats-grid dispensasi-stats">${metrics.map(([label, value, icon], index) => `<div class="stat-card ${index === 4 ? 'stat-success' : ''}"><div class="stat-info-wrapper"><span class="stat-label">${label}</span><span class="stat-value">${value}</span><span class="stat-trend neutral"><i class="fas ${icon}"></i> Berdasarkan data tersedia</span></div><div class="stat-icon"><i class="fas ${icon}"></i></div></div>`).join('')}</div><div class="charts-grid-equal"><div class="card-panel"><div class="card-header"><div><div class="card-title"><i class="fas fa-chart-line" style="color:var(--primary)"></i> Dispensasi per Bulan</div><div class="card-subtitle">Frekuensi pengajuan menurut waktu</div></div></div><div class="chart-card-wrapper"><canvas id="chartDispensasiTrend"></canvas></div></div><div class="card-panel"><div class="card-header"><div><div class="card-title"><i class="fas fa-building" style="color:var(--primary)"></i> Berdasarkan Unit Kerja</div><div class="card-subtitle">Distribusi pengajuan per unit</div></div></div><div class="chart-card-wrapper"><canvas id="chartDispensasiUnit"></canvas></div></div><div class="card-panel"><div class="card-header"><div><div class="card-title"><i class="fas fa-pie-chart" style="color:var(--accent-purple)"></i> Jenis Dispensasi</div><div class="card-subtitle">Kedinasan dan pribadi</div></div></div><div class="chart-card-wrapper"><canvas id="chartDispensasiJenis"></canvas></div></div><div class="card-panel"><div class="card-header"><div><div class="card-title"><i class="fas fa-chart-pie" style="color:var(--success)"></i> Status Dispensasi</div><div class="card-subtitle">Status proses dan penyelesaian</div></div></div><div class="chart-card-wrapper"><canvas id="chartDispensasiStatus"></canvas></div></div></div>`;
  },

  renderSummaryCharts() {
    const raw = this.state.rawData, fields = SchemaDetector.detectFields(raw), count = (pattern, classifier) => { const values = {}; raw.forEach(row => { const value = classifier ? classifier(row) : this.value(row, fields, pattern); if (value) values[value] = (values[value] || 0) + 1; }); return values; };
    const dateField = this.findField(fields, /timestamp|tanggal|tgl|mulai/i), months = {};
    raw.forEach(row => { const value = row[dateField]; if (!value) return; const parsed = new Date(value); const label = Number.isNaN(parsed.getTime()) ? String(value) : parsed.toLocaleString('id-ID', { month: 'short' }); months[label] = (months[label] || 0) + 1; });
    const unit = count(/unit|bidang|bagian/i), jenis = count(/jenis|kategori/i, row => this.classifyJenis(this.value(row, fields, /jenis|kategori/i))), status = count(/status/i);
    ChartEngine.createLineChart('chartDispensasiTrend', Object.keys(months), [{ label: 'Jumlah Dispensasi', data: Object.values(months), borderColor: ChartEngine.colors.primary, backgroundColor: 'rgba(15,76,129,.05)' }]);
    ChartEngine.createBarChart('chartDispensasiUnit', Object.keys(unit), [{ label: 'Dispensasi', data: Object.values(unit), backgroundColor: ChartEngine.colors.primary }]);
    ChartEngine.createDonutChart('chartDispensasiJenis', Object.keys(jenis), Object.values(jenis)); ChartEngine.createDonutChart('chartDispensasiStatus', Object.keys(status), Object.values(status));
  },

  logMarkup() { return `<div class="card-panel"><div class="card-header"><div><div class="card-title"><i class="fas fa-list-ul" style="color:var(--secondary)"></i> Log Dispensasi</div><div class="card-subtitle">Riwayat lengkap dari sheet log_dispensasi.</div></div><button class="btn btn-outline" id="dispensasiExportBtn"><i class="fas fa-file-csv"></i> Export CSV</button></div><div class="dispensasi-data-filters"><div class="search-wrapper"><i class="fas fa-search"></i><input type="search" id="dispensasiSearchInput" class="form-control" placeholder="Cari log dispensasi..."></div><select id="dispensasiFilterYear" class="form-select"><option value="Semua">Semua Tahun</option></select><select id="dispensasiFilterMonth" class="form-select"><option value="Semua">Semua Bulan</option>${['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'].map((month, index) => `<option value="${index + 1}">${month}</option>`).join('')}</select><select id="dispensasiFilterUnit" class="form-select"><option value="Semua">Semua Unit</option></select><select id="dispensasiFilterJenis" class="form-select"><option value="Semua">Semua Jenis</option></select><select id="dispensasiFilterStatus" class="form-select"><option value="Semua">Semua Status</option></select></div><div class="table-container"><div class="table-responsive"><table class="table" id="dispensasiLogTable"><thead><tr>${this.state.logFields.map(field => `<th class="sortable" data-col="${field}">${field} <i class="fas fa-sort"></i></th>`).join('')}</tr></thead><tbody id="dispensasiLogTableBody"></tbody></table></div><div class="table-controls" id="dispensasiLogTableControls"></div></div></div>`; },

  async loadLog() { const section = document.getElementById('dispensasiLogSection'); if (section) section.innerHTML = '<div class="investment-tab-loading"><i class="fas fa-circle-notch fa-spin"></i> Memuat log dispensasi...</div>'; try { const response = await API.request('getDispensasi', { sheet: 'log_dispensasi' }); if (!response.success) throw new Error(response.message || 'Gagal memuat log dispensasi.'); this.state.logData = Array.isArray(response.data) ? response.data : []; const fields = SchemaDetector.detectFields(this.state.logData); this.state.logFields = fields.length ? [...this.logColumns.filter(field => fields.includes(field)), ...fields.filter(field => !this.logColumns.includes(field) && field !== '_rowId')] : [...this.logColumns]; this.resetLogView(); this.renderLogSection(); } catch (error) { if (section) section.innerHTML = `<div class="investment-tab-error"><i class="fas fa-triangle-exclamation"></i><span>${error.message || 'Koneksi ke Google Spreadsheet gagal.'}</span><button class="btn btn-outline btn-sm" onclick="DispensasiModule.loadLog()">Coba Lagi</button></div>`; } },
  resetLogView() { Object.assign(this.state, { filteredData: [...this.state.logData], searchQuery: '', yearFilter: 'Semua', monthFilter: 'Semua', unitFilter: 'Semua', jenisFilter: 'Semua', statusFilter: 'Semua', sortColumn: null, sortDirection: 'asc', currentPage: 1 }); },
  logValue(row, pattern) { return this.value(row, this.state.logFields, pattern); },
  logPeriod(row) { const value = String(this.logValue(row, /timestamp|tanggal|tgl/i) || ''); const date = new Date(value); return { year: Number.isNaN(date.getTime()) ? (value.match(/\d{4}/) || [''])[0] : String(date.getFullYear()), month: Number.isNaN(date.getTime()) ? '' : String(date.getMonth() + 1) }; },
  populateLogFilters() { const options = (id, values, label) => { const element = document.getElementById(id); if (element) element.innerHTML = `<option value="Semua">Semua ${label}</option>` + [...new Set(values.filter(Boolean))].map(value => `<option value="${value}">${value}</option>`).join(''); }; options('dispensasiFilterYear', this.state.logData.map(row => this.logPeriod(row).year), 'Tahun'); options('dispensasiFilterUnit', this.state.logData.map(row => this.logValue(row, /unit|bidang/i)), 'Unit'); options('dispensasiFilterJenis', this.state.logData.map(row => this.logValue(row, /jenis.*dispensasi|jenis/i)), 'Jenis'); options('dispensasiFilterStatus', this.state.logData.map(row => this.logValue(row, /status/i)), 'Status'); },
  applyLogFilters() { const state = this.state; state.filteredData = state.logData.filter(row => { const period = this.logPeriod(row); return (!state.searchQuery || Object.values(row).join(' ').toLowerCase().includes(state.searchQuery.toLowerCase())) && (state.yearFilter === 'Semua' || period.year === state.yearFilter) && (state.monthFilter === 'Semua' || period.month === state.monthFilter) && (state.unitFilter === 'Semua' || String(this.logValue(row, /unit|bidang/i)) === state.unitFilter) && (state.jenisFilter === 'Semua' || String(this.logValue(row, /jenis.*dispensasi|jenis/i)) === state.jenisFilter) && (state.statusFilter === 'Semua' || String(this.logValue(row, /status/i)) === state.statusFilter); }); if (state.sortColumn) this.sortLog(); state.currentPage = 1; this.renderLogTable(); },
  sortLog() { const state = this.state, dir = state.sortDirection === 'asc' ? 1 : -1; state.filteredData.sort((a, b) => String(a[state.sortColumn] ?? '').localeCompare(String(b[state.sortColumn] ?? ''), 'id', { numeric: true }) * dir); },
  renderLogTable() { const body = document.getElementById('dispensasiLogTableBody'), controls = document.getElementById('dispensasiLogTableControls'); if (!body || !controls) return; const state = this.state, total = state.filteredData.length, pages = Math.max(1, Math.ceil(total / state.pageSize)); state.currentPage = Math.min(state.currentPage, pages); const start = (state.currentPage - 1) * state.pageSize, rows = state.filteredData.slice(start, start + state.pageSize); body.innerHTML = rows.length ? rows.map(row => `<tr>${state.logFields.map(field => { const value = row[field] ?? ''; if (/timestamp|tanggal|tgl/i.test(field)) return `<td>${Utils.formatDate(value, /timestamp/i.test(field))}</td>`; if (/status/i.test(field)) return `<td>${Utils.getStatusBadge(value)}</td>`; return `<td>${value}</td>`; }).join('')}</tr>`).join('') : `<tr><td colspan="${Math.max(1,state.logFields.length)}"><div class="empty-state"><i class="fas fa-folder-open"></i><div class="empty-state-title">Tidak ada log dispensasi</div><div class="empty-state-text">Ubah filter pencarian Anda.</div></div></td></tr>`; if (!total) { controls.innerHTML = ''; return; } const numbers = [], first = Math.max(1,state.currentPage-2), last = Math.min(pages,first+4); for(let page=first;page<=last;page++) numbers.push(page); controls.innerHTML = `<div class="table-info-text">Menampilkan <strong>${start+1}–${Math.min(start+state.pageSize,total)}</strong> dari <strong>${total}</strong> data</div><div class="pagination"><button class="page-btn" data-log-page="1" ${state.currentPage===1?'disabled':''}>First</button><button class="page-btn" data-log-page="${state.currentPage-1}" ${state.currentPage===1?'disabled':''}>Previous</button>${numbers.map(page=>`<button class="page-btn ${page===state.currentPage?'active':''}" data-log-page="${page}">${page}</button>`).join('')}<button class="page-btn" data-log-page="${state.currentPage+1}" ${state.currentPage===pages?'disabled':''}>Next</button><button class="page-btn" data-log-page="${pages}" ${state.currentPage===pages?'disabled':''}>Last</button></div>`; controls.querySelectorAll('[data-log-page]').forEach(button=>button.addEventListener('click',()=>{state.currentPage=Number(button.dataset.logPage);this.renderLogTable();})); },
  bindLogEvents() { const state=this.state; const map={dispensasiSearchInput:'searchQuery',dispensasiFilterYear:'yearFilter',dispensasiFilterMonth:'monthFilter',dispensasiFilterUnit:'unitFilter',dispensasiFilterJenis:'jenisFilter',dispensasiFilterStatus:'statusFilter'}; Object.entries(map).forEach(([id,key])=>{const element=document.getElementById(id);if(element)element.addEventListener(id==='dispensasiSearchInput'?'input':'change',event=>{state[key]=event.target.value;this.applyLogFilters();});}); document.querySelectorAll('#dispensasiLogTable th.sortable').forEach(header=>header.addEventListener('click',()=>{state.sortDirection=state.sortColumn===header.dataset.col&&state.sortDirection==='asc'?'desc':'asc';state.sortColumn=header.dataset.col;this.applyLogFilters();})); const exportButton=document.getElementById('dispensasiExportBtn');if(exportButton)exportButton.addEventListener('click',()=>Utils.exportToCSV('Log_Dispensasi_DPMPTSP',[state.logFields,...state.filteredData.map(row=>state.logFields.map(field=>row[field]))])); }
};
